version: '3.7'

services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    networks:
      - proxy-net
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    depends_on:
      - api
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    restart: always
    deploy:
      placement:
        constraints:
          - node.role==manager
          # - node.hostname == ${HOSTNAMEs}

  mongo:
    image: mongo
    ports: 
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - proxy-net
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=ilovedocker
    secrets:
      - db_password
    deploy:
      labels:
        traefik.backend: "front"
        traefik.port: "27017"
        traefik.frontend.rule: "PathPrefix:/"
        traefik.docker.network: "proxy-net"
      restart_policy: 
        condition: on-failure
    
  reverse-proxy:
    image: traefik
    command: --api --docker --docker.swarmMode
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - proxy-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints: [node.role == manager]
      labels:
        traefik.docker.network: "proxy-net"

  api:
    image: christerence/blabber-api:latest
    read_only: true
    volumes:
      - .:/app
    depends_on:
      - mongo
    networks:
      - proxy-net
    working_dir: /usr/src/app
    environment:
      API_MONGO_USER: "user"
      API_MONGO_PASSWORD_FILE: /run/secrets/db_password
    command: "npm run start"
    ports:
      - "3000:3000"
    secrets:
      - db_password
    deploy:
      replicas: 2
      labels:
        traefik.backend: "api"
        traefik.frontend.rule: "PathPrefix:/api"
        traefik.port: "3000"
        traefik.frontend.rule: "PathPrefixStrip:/api"
        traefik.docker.network: "proxy-net"
      restart_policy:
        condition: on-failure

  front:
    image: vtcs2304s19/blabber-client
    networks:
      - proxy-net
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      labels:
        traefik.backend: "front"
        traefik.port: "80"
        traefik.frontend.rule: "PathPrefix:/"
        traefik.docker.network: "proxy-net"


  visualizer:
    image: mikesir87/swarm-viz
    ports:
      - "5000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure

volumes:
 mongo-data:
 prometheus_data:
 prometheus_config_data:

secrets:
  db_password:
    file: ./db_password.txt

networks:
  proxy-net:
    name: "proxy-net"
    driver: overlay