version: '3.7'

services:

  mongo:
    image: mongo
    ports: 
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    
  reverse-proxy:
    image: traefik
    command: --api --docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  api:
    build: ./
    volumes:
      - .:/app
    depends_on:
      - mongo
    working_dir: /app
    environment:
      NODE_ENV: development
      WAIT_HOSTS: mongo:27017
    command: "npm run start"
    ports:
      - "3000:3000"
    labels:
      traefik.backend: "api"
      traefik.frontend.rule: "PathPrefix:/api"
      traefik.port: "3000"
      traefik.frontend.rule: "PathPrefixStrip:/api"

  front:
    image: vtcs2304s19/blabber-client
    labels:
      traefik.backend: "front"
      traefik.port: "80"
      traefik.frontend.rule: "Host:front.docker.localhost"
      traefik.frontend.rule: "PathPrefix:/"
  
  tests:
    image: vtcs2304s19/blabber-api-tests
    environment:
      SERVICE_NAME: api
      API_PORT: "3000"
      SLEEP_TIMER: 5000
      WAIT_HOSTS: mongo:27017
    depends_on:
      - api


volumes:
 mongo-data:
